//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.Common.RestHelp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.Common.RestHelp.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint address &apos;{0}&apos; has message headers and is being used with a binding that&apos;s configured for message version None. Either change the endpoint address to not contain message headers or change the binding to be one that supports SOAP (for example, WSHttpBinding)..
        /// </summary>
        internal static string E_REST_HELP_CANNOT_HAVE_MESSAGE_HEADER {
            get {
                return ResourceManager.GetString("E_REST_HELP_CANNOT_HAVE_MESSAGE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint is null.
        /// </summary>
        internal static string E_REST_HELP_ENDPOINT_IS_NULL {
            get {
                return ResourceManager.GetString("E_REST_HELP_ENDPOINT_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint at &apos;{0}&apos; does not have a Binding with the None MessageVersion.  &apos;{1}&apos; is only intended for use with WebHttpBinding or similar bindings..
        /// </summary>
        internal static string E_REST_HELP_INVALID_MESSAGE_VERSION {
            get {
                return ResourceManager.GetString("E_REST_HELP_INVALID_MESSAGE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint at &apos;{0}&apos; does not have a Binding with Scheme &apos;http&apos; or &apos;https&apos;.  &apos;{1}&apos; is only intended for use with WebHttpBinding or similar bindings..
        /// </summary>
        internal static string E_REST_HELP_INVALID_SCHEME {
            get {
                return ResourceManager.GetString("E_REST_HELP_INVALID_SCHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the endpoint at &apos;{0}&apos;, in order to use &apos;{1}&apos;, the &apos;{2}&apos; of the binding must have ManualAddressing set to true..
        /// </summary>
        internal static string E_REST_HELP_NEED_MANUAL_ADDRESSING {
            get {
                return ResourceManager.GetString("E_REST_HELP_NEED_MANUAL_ADDRESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected boolean type value for required flag, but was &apos;{0}&apos;..
        /// </summary>
        internal static string E_REST_HELP_PARSE_OPTIONAL_VALUE {
            get {
                return ResourceManager.GetString("E_REST_HELP_PARSE_OPTIONAL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occrred while generating Swagger REST help..
        /// </summary>
        internal static string E_SWAGGER_HELP_GENERATING_ERROR {
            get {
                return ResourceManager.GetString("E_SWAGGER_HELP_GENERATING_ERROR", resourceCulture);
            }
        }
    }
}
