//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.Common.RestHelp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.Common.RestHelp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_closed {
            get {
                object obj = ResourceManager.GetObject("folder_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler for type {0} not found..
        /// </summary>
        internal static string HelpExampleGeneratorHandlerNotFound {
            get {
                return ResourceManager.GetString("HelpExampleGeneratorHandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-us.
        /// </summary>
        internal static string HelpExampleGeneratorLanguage {
            get {
                return ResourceManager.GetString("HelpExampleGeneratorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max depth level reached at {0}..
        /// </summary>
        internal static string HelpExampleGeneratorMaxDepthLevelReached {
            get {
                return ResourceManager.GetString("HelpExampleGeneratorMaxDepthLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema object {0} not supported..
        /// </summary>
        internal static string HelpExampleGeneratorSchemaObjectNotSupported {
            get {
                return ResourceManager.GetString("HelpExampleGeneratorSchemaObjectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String content.
        /// </summary>
        internal static string HelpExampleGeneratorStringContent {
            get {
                return ResourceManager.GetString("HelpExampleGeneratorStringContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element contains text..
        /// </summary>
        internal static string HelpExampleGeneratorThisElementContainsText {
            get {
                return ResourceManager.GetString("HelpExampleGeneratorThisElementContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional request Xml Schemas:.
        /// </summary>
        internal static string HelpPageAdditionalRequestSchema {
            get {
                return ResourceManager.GetString("HelpPageAdditionalRequestSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional response Xml Schemas:.
        /// </summary>
        internal static string HelpPageAdditionalResponseSchema {
            get {
                return ResourceManager.GetString("HelpPageAdditionalResponseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Uri:.
        /// </summary>
        internal static string HelpPageBaseUri {
            get {
                return ResourceManager.GetString("HelpPageBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmask enumeration.
        /// </summary>
        internal static string HelpPageBimaskEnumeration {
            get {
                return ResourceManager.GetString("HelpPageBimaskEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} body is empty..
        /// </summary>
        internal static string HelpPageBodyIsEmpty {
            get {
                return ResourceManager.GetString("HelpPageBodyIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot infer schema. The {0} body is wrapped..
        /// </summary>
        internal static string HelpPageBodyIsWrapped {
            get {
                return ResourceManager.GetString("HelpPageBodyIsWrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string HelpPageBoolean {
            get {
                return ResourceManager.GetString("HelpPageBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        internal static string HelpPageContractDescription {
            get {
                return ResourceManager.GetString("HelpPageContractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations: .
        /// </summary>
        internal static string HelpPageContractOperationList {
            get {
                return ResourceManager.GetString("HelpPageContractOperationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST help.
        /// </summary>
        internal static string HelpPageContractTitle {
            get {
                return ResourceManager.GetString("HelpPageContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate schema document..
        /// </summary>
        internal static string HelpPageCouldNotGenerateSchema {
            get {
                return ResourceManager.GetString("HelpPageCouldNotGenerateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/css.
        /// </summary>
        internal static string HelpPageCss {
            get {
                return ResourceManager.GetString("HelpPageCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string HelpPageDateTimeString {
            get {
                return ResourceManager.GetString("HelpPageDateTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        internal static string HelpPageDescription {
            get {
                return ResourceManager.GetString("HelpPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of key-value pair.
        /// </summary>
        internal static string HelpPageDictionary {
            get {
                return ResourceManager.GetString("HelpPageDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration.
        /// </summary>
        internal static string HelpPageEnumeration {
            get {
                return ResourceManager.GetString("HelpPageEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code {0} ({1}) response example:.
        /// </summary>
        internal static string HelpPageErrorResponseExampleTitle {
            get {
                return ResourceManager.GetString("HelpPageErrorResponseExampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string HelpPageExample {
            get {
                return ResourceManager.GetString("HelpPageExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples: .
        /// </summary>
        internal static string HelpPageExamples {
            get {
                return ResourceManager.GetString("HelpPageExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float numeric.
        /// </summary>
        internal static string HelpPageFloatNumeric {
            get {
                return ResourceManager.GetString("HelpPageFloatNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operations list.
        /// </summary>
        internal static string HelpPageHome {
            get {
                return ResourceManager.GetString("HelpPageHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/gif.
        /// </summary>
        internal static string HelpPageImageGif {
            get {
                return ResourceManager.GetString("HelpPageImageGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Body parameters.
        /// </summary>
        internal static string HelpPageInputBodyParameters {
            get {
                return ResourceManager.GetString("HelpPageInputBodyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Query parameters.
        /// </summary>
        internal static string HelpPageInputQueryParameters {
            get {
                return ResourceManager.GetString("HelpPageInputQueryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Uri parameters.
        /// </summary>
        internal static string HelpPageInputUrlParameters {
            get {
                return ResourceManager.GetString("HelpPageInputUrlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/javascript.
        /// </summary>
        internal static string HelpPageJavascript {
            get {
                return ResourceManager.GetString("HelpPageJavascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is an example error response Json body:.
        /// </summary>
        internal static string HelpPageJsonErrorResponse {
            get {
                return ResourceManager.GetString("HelpPageJsonErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON object.
        /// </summary>
        internal static string HelpPageJsonObject {
            get {
                return ResourceManager.GetString("HelpPageJsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is an example request Json body:.
        /// </summary>
        internal static string HelpPageJsonRequest {
            get {
                return ResourceManager.GetString("HelpPageJsonRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is an example response Json body:.
        /// </summary>
        internal static string HelpPageJsonResponse {
            get {
                return ResourceManager.GetString("HelpPageJsonResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method: .
        /// </summary>
        internal static string HelpPageMethod {
            get {
                return ResourceManager.GetString("HelpPageMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string HelpPageNA {
            get {
                return ResourceManager.GetString("HelpPageNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation name: .
        /// </summary>
        internal static string HelpPageName {
            get {
                return ResourceManager.GetString("HelpPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nullable.
        /// </summary>
        internal static string HelpPageNullable {
            get {
                return ResourceManager.GetString("HelpPageNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string HelpPageNumeric {
            get {
                return ResourceManager.GetString("HelpPageNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation: .
        /// </summary>
        internal static string HelpPageOperation {
            get {
                return ResourceManager.GetString("HelpPageOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p  xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;b&gt;HTTP Method: &lt;/b&gt;&lt;span class=&quot;method&quot;&gt;{0}&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        internal static string HelpPageOperationMethod {
            get {
                return ResourceManager.GetString("HelpPageOperationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation: .
        /// </summary>
        internal static string HelpPageOperationName {
            get {
                return ResourceManager.GetString("HelpPageOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to operations list.
        /// </summary>
        internal static string HelpPageOperationsAt {
            get {
                return ResourceManager.GetString("HelpPageOperationsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST operation help.
        /// </summary>
        internal static string HelpPageOperationTitle {
            get {
                return ResourceManager.GetString("HelpPageOperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p  xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;b&gt;Url: &lt;/b&gt;&lt;span class=&quot;uri-template&quot;&gt;{0}&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        internal static string HelpPageOperationUri {
            get {
                return ResourceManager.GetString("HelpPageOperationUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string HelpPageOutputFailure {
            get {
                return ResourceManager.GetString("HelpPageOutputFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output parameters.
        /// </summary>
        internal static string HelpPageOutputParameters {
            get {
                return ResourceManager.GetString("HelpPageOutputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string HelpPageOutputSuccess {
            get {
                return ResourceManager.GetString("HelpPageOutputSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string HelpPageParameterName {
            get {
                return ResourceManager.GetString("HelpPageParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Place: .
        /// </summary>
        internal static string HelpPageParameterPlace {
            get {
                return ResourceManager.GetString("HelpPageParameterPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters: .
        /// </summary>
        internal static string HelpPageParameters {
            get {
                return ResourceManager.GetString("HelpPageParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (undefined).
        /// </summary>
        internal static string HelpPageParameterUndefiner {
            get {
                return ResourceManager.GetString("HelpPageParameterUndefiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0}.
        /// </summary>
        internal static string HelpPageReferenceFor {
            get {
                return ResourceManager.GetString("HelpPageReferenceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string HelpPageRequest {
            get {
                return ResourceManager.GetString("HelpPageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Error.
        /// </summary>
        internal static string HelpPageRequestErrorTitle {
            get {
                return ResourceManager.GetString("HelpPageRequestErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is the request Xml Schema:.
        /// </summary>
        internal static string HelpPageRequestSchema {
            get {
                return ResourceManager.GetString("HelpPageRequestSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string HelpPageResponse {
            get {
                return ResourceManager.GetString("HelpPageResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is the response Xml Schema:.
        /// </summary>
        internal static string HelpPageResponseSchema {
            get {
                return ResourceManager.GetString("HelpPageResponseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Codes:.
        /// </summary>
        internal static string HelpPageResponseTitle {
            get {
                return ResourceManager.GetString("HelpPageResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return exception: .
        /// </summary>
        internal static string HelpPageReturnErrorValue {
            get {
                return ResourceManager.GetString("HelpPageReturnErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return value: .
        /// </summary>
        internal static string HelpPageReturnValue {
            get {
                return ResourceManager.GetString("HelpPageReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string HelpPageSchema {
            get {
                return ResourceManager.GetString("HelpPageSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page describes the service operations at this endpoint..
        /// </summary>
        internal static string HelpPageStaticText {
            get {
                return ResourceManager.GetString("HelpPageStaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string HelpPageString {
            get {
                return ResourceManager.GetString("HelpPageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successfull.
        /// </summary>
        internal static string HelpPageSuccessOperationDescription {
            get {
                return ResourceManager.GetString("HelpPageSuccessOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string HelpPageTableDescription {
            get {
                return ResourceManager.GetString("HelpPageTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string HelpPageTableMethod {
            get {
                return ResourceManager.GetString("HelpPageTableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation name.
        /// </summary>
        internal static string HelpPageTableName {
            get {
                return ResourceManager.GetString("HelpPageTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        internal static string HelpPageTableUri {
            get {
                return ResourceManager.GetString("HelpPageTableUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        internal static string HelpPageTextHtml {
            get {
                return ResourceManager.GetString("HelpPageTextHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string HelpPageUnknown {
            get {
                return ResourceManager.GetString("HelpPageUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri: .
        /// </summary>
        internal static string HelpPageUri {
            get {
                return ResourceManager.GetString("HelpPageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid elements of type: {0}.
        /// </summary>
        internal static string HelpPageValidElementOfType {
            get {
                return ResourceManager.GetString("HelpPageValidElementOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xml.
        /// </summary>
        internal static string HelpPageXml {
            get {
                return ResourceManager.GetString("HelpPageXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information of the contract in XML format.
        /// </summary>
        internal static string HelpPageXmlRefValue {
            get {
                return ResourceManager.GetString("HelpPageXmlRefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is an example request Xml body:.
        /// </summary>
        internal static string HelpPageXmlRequest {
            get {
                return ResourceManager.GetString("HelpPageXmlRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is an example response Xml body:.
        /// </summary>
        internal static string HelpPageXmlResponse {
            get {
                return ResourceManager.GetString("HelpPageXmlResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function (a, b) { &quot;object&quot; == typeof module &amp;&amp; &quot;object&quot; == typeof module.exports ? module.exports = a.document ? b(a, !0) : function (a) { if (!a.document) throw new Error(&quot;jQuery requires a window with a document&quot;); return b(a) } : b(a) }(&quot;undefined&quot; != typeof window ? window : this, function (a, b) {
        ///    var c = [], d = a.document, e = c.slice, f = c.concat, g = c.push, h = c.indexOf, i = {}, j = i.toString, k = i.hasOwnProperty, l = {}, m = &quot;1.12.4&quot;, n = function (a, b) { return new n.fn.init(a, b) },  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_3_2_1_min {
            get {
                return ResourceManager.GetString("jquery_3_2_1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .treeview, .treeview ul {
        ///	padding: 0;
        ///	margin: 0;
        ///	list-style: none;
        ///}
        ///
        ///.treeview ul {
        ///	background-color: white;
        ///	margin-top: 4px;
        ///}
        ///
        ///.treeview .hitarea {
        ///	background: url(Images/treeview_default.gif) -64px -25px no-repeat;
        ///	height: 16px;
        ///	width: 16px;
        ///	margin-left: -16px;
        ///	float: left;
        ///	cursor: pointer;
        ///}
        ////* fix for IE6 */
        ///* html .hitarea {
        ///	display: inline;
        ///	float:none;
        ///}
        ///
        ///.treeview li {
        ///	margin: 0;
        ///	padding: 3px 0pt 3px 16px;
        ///}
        ///
        ///.treeview a.selected {
        ///	background-color: #e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_treeview_css {
            get {
                return ResourceManager.GetString("jquery_treeview_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Treeview 1.4.2 - jQuery plugin to hide and show branches of a tree
        /// *
        /// * http://bassistance.de/jquery-plugins/jquery-plugin-treeview/
        /// *
        /// * Copyright Jörn Zaefferer
        /// * Released under the MIT license:
        /// *   http://www.opensource.org/licenses/mit-license.php
        /// */
        ///
        ///;(function($) {
        ///
        ///	// TODO rewrite as a widget, removing all the extra plugins
        ///	$.extend($.fn, {
        ///		swapClass: function(c1, c2) {
        ///			var c1Elements = this.filter(&apos;.&apos; + c1);
        ///			this.filter(&apos;.&apos; + c2).removeClass(c2).addClass(c1);
        ///			c1Elements.remov [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_treeview_js {
            get {
                return ResourceManager.GetString("jquery_treeview_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$(document).ready(function () {
        ///    $(&quot;#inputOperation&quot;).treeview({ collapsed: true });        
        ///    $(&quot;#outputOperation&quot;).treeview({ collapsed: true });
        ///    $(&quot;.folder&quot;).each(function () { $(this).click(); });
        ///});.
        /// </summary>
        internal static string scripts {
            get {
                return ResourceManager.GetString("scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BODY {
        ///    color: #000000;
        ///    background-color: white;
        ///    font-family: Verdana;
        ///    margin-left: 0px;
        ///    margin-top: 0px;
        ///}
        ///
        ///#content {
        ///    margin-left: 30px;
        ///    font-size: .70em;
        ///    padding-bottom: 2em;
        ///}
        ///
        ///A:link {
        ///    color: #336699;
        ///    font-weight: bold;
        ///    text-decoration: underline;
        ///}
        ///
        ///A:visited {
        ///    color: #6699cc;
        ///    font-weight: bold;
        ///    text-decoration: underline;
        ///}
        ///
        ///A:active {
        ///    color: #336699;
        ///    font-weight: bold;
        ///    text-decoration: underline;
        ///}
        ///
        ///.h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles {
            get {
                return ResourceManager.GetString("styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap treeview_default {
            get {
                object obj = ResourceManager.GetObject("treeview_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap treeview_default_line {
            get {
                object obj = ResourceManager.GetObject("treeview_default_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
